apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: location-shared
data:
  NEXT_PUBLIC_API_BASE_URL: http://api.location-shared.4.231.68.185.sslip.io
  CORS_ORIGINS: http://location-shared.4.231.68.185.sslip.io
  API_V1_PREFIX: /api/v1
