apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: location-shared
  namespace: location-shared
spec:
  ingressClassName: nginx
  rules:
    - host: location-shared.4.231.68.185.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.location-shared.4.231.68.185.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
